package com.julia.szelesjulia.myapplication.datamodel

import com.google.gson.annotations.SerializedName

/**
 * Currency types model
 */
data class CurrencyModel (
    @SerializedName("success")
    val success: Boolean,

    @SerializedName("terms")
    val terms: String,

    @SerializedName("privacy")
    val privacy: String,

    @SerializedName("currencies")
    val currencies: CurrencyListItems
)

data class CurrencyListItems(
    @SerializedName("AED") val aED: String,
    @SerializedName("AFN") val aFN: String,
    @SerializedName("ALL") val aLL: String,
    @SerializedName("AMD") val aMD: String,
    @SerializedName("ANG") val aNG: String,
    @SerializedName("AOA") val aOA: String,
    @SerializedName("ARS") val aRS: String,
    @SerializedName("AUD") val aUD: String,
    @SerializedName("AWG") val aWG: String,
    @SerializedName("AZN") val aZN: String,
    @SerializedName("BAM") val bAM: String,
    @SerializedName("BBD") val bBD: String,
    @SerializedName("BDT") val bDT: String,
    @SerializedName("BGN") val bGN: String,
    @SerializedName("BHD") val bHD: String,
    @SerializedName("BIF") val bIF: String,
    @SerializedName("BMD") val bMD: String,
    @SerializedName("BND") val bND: String,
    @SerializedName("BOB") val bOB: String,
    @SerializedName("BRL") val bRL: String,
    @SerializedName("BSD") val bSD: String,
    @SerializedName("BTC") val bTC: String,
    @SerializedName("BTN") val bTN: String,
    @SerializedName("BWP") val bWP: String,
    @SerializedName("BYN") val bYN: String,
    @SerializedName("BYR") val bYR: String,
    @SerializedName("BZD") val bZD: String,
    @SerializedName("CAD") val cAD: String,
    @SerializedName("CDF") val cDF: String,
    @SerializedName("CHF") val cHF: String,
    @SerializedName("CLF") val cLF: String,
    @SerializedName("CLP") val cLP: String,
    @SerializedName("CNY") val cNY: String,
    @SerializedName("COP") val cOP: String,
    @SerializedName("CRC") val cRC: String,
    @SerializedName("CUC") val cUC: String,
    @SerializedName("CUP") val cUP: String,
    @SerializedName("CVE") val cVE: String,
    @SerializedName("CZK") val cZK: String,
    @SerializedName("DJF") val dJF: String,
    @SerializedName("DKK") val dKK: String,
    @SerializedName("DOP") val dOP: String,
    @SerializedName("DZD") val dZD: String,
    @SerializedName("EGP") val eGP: String,
    @SerializedName("ERN") val eRN: String,
    @SerializedName("ETB") val eTB: String,
    @SerializedName("EUR") val eUR: String,
    @SerializedName("FJD") val fJD: String,
    @SerializedName("FKP") val fKP: String,
    @SerializedName("GBP") val gBP: String,
    @SerializedName("GEL") val gEL: String,
    @SerializedName("GGP") val gGP: String,
    @SerializedName("GHS") val gHS: String,
    @SerializedName("GIP") val gIP: String,
    @SerializedName("GMD") val gMD: String,
    @SerializedName("GNF") val gNF: String,
    @SerializedName("GTQ") val gTQ: String,
    @SerializedName("GYD") val gYD: String,
    @SerializedName("HKD") val hKD: String,
    @SerializedName("HNL") val hNL: String,
    @SerializedName("HRK") val hRK: String,
    @SerializedName("HTG") val hTG: String,
    @SerializedName("HUF") val hUF: String,
    @SerializedName("IDR") val iDR: String,
    @SerializedName("ILS") val iLS: String,
    @SerializedName("IMP") val iMP: String,
    @SerializedName("INR") val iNR: String,
    @SerializedName("IQD") val iQD: String,
    @SerializedName("IRR") val iRR: String,
    @SerializedName("ISK") val iSK: String,
    @SerializedName("JEP") val jEP: String,
    @SerializedName("JMD") val jMD: String,
    @SerializedName("JOD") val jOD: String,
    @SerializedName("JPY") val jPY: String,
    @SerializedName("KES") val kES: String,
    @SerializedName("KGS") val kGS: String,
    @SerializedName("KHR") val kHR: String,
    @SerializedName("KMF") val kMF: String,
    @SerializedName("KPW") val kPW: String,
    @SerializedName("KRW") val kRW: String,
    @SerializedName("KWD") val kWD: String,
    @SerializedName("KYD") val kYD: String,
    @SerializedName("KZT") val kZT: String,
    @SerializedName("LAK") val lAK: String,
    @SerializedName("LBP") val lBP: String,
    @SerializedName("LKR") val lKR: String,
    @SerializedName("LRD") val lRD: String,
    @SerializedName("LSL") val lSL: String,
    @SerializedName("LTL") val lTL: String,
    @SerializedName("LVL") val lVL: String,
    @SerializedName("LYD") val lYD: String,
    @SerializedName("MAD") val mAD: String,
    @SerializedName("MDL") val mDL: String,
    @SerializedName("MGA") val mGA: String,
    @SerializedName("MKD") val mKD: String,
    @SerializedName("MMK") val mMK: String,
    @SerializedName("MNT") val mNT: String,
    @SerializedName("MOP") val mOP: String,
    @SerializedName("MRO") val mRO: String,
    @SerializedName("MUR") val mUR: String,
    @SerializedName("MVR") val mVR: String,
    @SerializedName("MWK") val mWK: String,
    @SerializedName("MXN") val mXN: String,
    @SerializedName("MYR") val mYR: String,
    @SerializedName("MZN") val mZN: String,
    @SerializedName("NAD") val nAD: String,
    @SerializedName("NGN") val nGN: String,
    @SerializedName("NIO") val nIO: String,
    @SerializedName("NOK") val nOK: String,
    @SerializedName("NPR") val nPR: String,
    @SerializedName("NZD") val nZD: String,
    @SerializedName("OMR") val oMR: String,
    @SerializedName("PAB") val pAB: String,
    @SerializedName("PEN") val pEN: String
)